/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.gebhard.qa.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Answer service. Represents a row in the &quot;QuickAnswer_Answer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.gebhard.qa.model.impl.AnswerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.gebhard.qa.model.impl.AnswerImpl}.
 * </p>
 *
 * @author Philipp Gebhard
 * @see Answer
 * @see it.gebhard.qa.model.impl.AnswerImpl
 * @see it.gebhard.qa.model.impl.AnswerModelImpl
 * @generated
 */
public interface AnswerModel extends BaseModel<Answer> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a Answer model instance should use the {@link Answer} interface instead.
	 */

	/**
	 * Returns the primary key of this Answer.
	 *
	 * @return the primary key of this Answer
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this Answer.
	 *
	 * @param primaryKey the primary key of this Answer
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the answer ID of this Answer.
	 *
	 * @return the answer ID of this Answer
	 */
	public long getAnswerId();

	/**
	 * Sets the answer ID of this Answer.
	 *
	 * @param answerId the answer ID of this Answer
	 */
	public void setAnswerId(long answerId);

	/**
	 * Returns the question ID of this Answer.
	 *
	 * @return the question ID of this Answer
	 */
	public long getQuestionId();

	/**
	 * Sets the question ID of this Answer.
	 *
	 * @param questionId the question ID of this Answer
	 */
	public void setQuestionId(long questionId);

	/**
	 * Returns the user ID of this Answer.
	 *
	 * @return the user ID of this Answer
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this Answer.
	 *
	 * @param userId the user ID of this Answer
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this Answer.
	 *
	 * @return the user uuid of this Answer
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this Answer.
	 *
	 * @param userUuid the user uuid of this Answer
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the message of this Answer.
	 *
	 * @return the message of this Answer
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this Answer.
	 *
	 * @param message the message of this Answer
	 */
	public void setMessage(String message);

	/**
	 * Returns the guest user ID of this Answer.
	 *
	 * @return the guest user ID of this Answer
	 */
	public long getGuestUserId();

	/**
	 * Sets the guest user ID of this Answer.
	 *
	 * @param guestUserId the guest user ID of this Answer
	 */
	public void setGuestUserId(long guestUserId);

	/**
	 * Returns the guest user uuid of this Answer.
	 *
	 * @return the guest user uuid of this Answer
	 * @throws SystemException if a system exception occurred
	 */
	public String getGuestUserUuid() throws SystemException;

	/**
	 * Sets the guest user uuid of this Answer.
	 *
	 * @param guestUserUuid the guest user uuid of this Answer
	 */
	public void setGuestUserUuid(String guestUserUuid);

	/**
	 * Returns the created of this Answer.
	 *
	 * @return the created of this Answer
	 */
	public Date getCreated();

	/**
	 * Sets the created of this Answer.
	 *
	 * @param created the created of this Answer
	 */
	public void setCreated(Date created);

	/**
	 * Returns the modified of this Answer.
	 *
	 * @return the modified of this Answer
	 */
	public Date getModified();

	/**
	 * Sets the modified of this Answer.
	 *
	 * @param modified the modified of this Answer
	 */
	public void setModified(Date modified);

	/**
	 * Returns the accepted of this Answer.
	 *
	 * @return the accepted of this Answer
	 */
	public boolean getAccepted();

	/**
	 * Returns <code>true</code> if this Answer is accepted.
	 *
	 * @return <code>true</code> if this Answer is accepted; <code>false</code> otherwise
	 */
	public boolean isAccepted();

	/**
	 * Sets whether this Answer is accepted.
	 *
	 * @param accepted the accepted of this Answer
	 */
	public void setAccepted(boolean accepted);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Answer answer);

	public int hashCode();

	public CacheModel<Answer> toCacheModel();

	public Answer toEscapedModel();

	public String toString();

	public String toXmlString();
}