/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.gebhard.qa.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import it.gebhard.qa.model.Tag;
import it.gebhard.qa.model.TagModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Tag service. Represents a row in the &quot;QuickAnswer_Tag&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link it.gebhard.qa.model.TagModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TagImpl}.
 * </p>
 *
 * @author Philipp Gebhard
 * @see TagImpl
 * @see it.gebhard.qa.model.Tag
 * @see it.gebhard.qa.model.TagModel
 * @generated
 */
public class TagModelImpl extends BaseModelImpl<Tag> implements TagModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a Tag model instance should use the {@link it.gebhard.qa.model.Tag} interface instead.
	 */
	public static final String TABLE_NAME = "QuickAnswer_Tag";
	public static final Object[][] TABLE_COLUMNS = {
			{ "tagId", Types.BIGINT },
			{ "name", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table QuickAnswer_Tag (tagId LONG not null primary key,name VARCHAR(100) null)";
	public static final String TABLE_SQL_DROP = "drop table QuickAnswer_Tag";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.it.gebhard.qa.model.Tag"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.it.gebhard.qa.model.Tag"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.it.gebhard.qa.model.Tag"),
			true);
	public static long NAME_COLUMN_BITMASK = 1L;
	public static final String MAPPING_TABLE_QUICKANSWER_QUESTIONTAG_NAME = "QuickAnswer_QuestionTag";
	public static final Object[][] MAPPING_TABLE_QUICKANSWER_QUESTIONTAG_COLUMNS =
		{
			{ "questionId", Types.BIGINT },
			{ "tagId", Types.BIGINT }
		};
	public static final String MAPPING_TABLE_QUICKANSWER_QUESTIONTAG_SQL_CREATE = "create table QuickAnswer_QuestionTag (questionId LONG not null,tagId LONG not null,primary key (questionId, tagId))";
	public static final boolean FINDER_CACHE_ENABLED_QUICKANSWER_QUESTIONTAG = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.QuickAnswer_QuestionTag"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.it.gebhard.qa.model.Tag"));

	public TagModelImpl() {
	}

	public long getPrimaryKey() {
		return _tagId;
	}

	public void setPrimaryKey(long primaryKey) {
		setTagId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_tagId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return Tag.class;
	}

	public String getModelClassName() {
		return Tag.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("tagId", getTagId());
		attributes.put("name", getName());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long tagId = (Long)attributes.get("tagId");

		if (tagId != null) {
			setTagId(tagId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}
	}

	public long getTagId() {
		return _tagId;
	}

	public void setTagId(long tagId) {
		_tagId = tagId;
	}

	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Tag.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Tag toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Tag)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		TagImpl tagImpl = new TagImpl();

		tagImpl.setTagId(getTagId());
		tagImpl.setName(getName());

		tagImpl.resetOriginalValues();

		return tagImpl;
	}

	public int compareTo(Tag tag) {
		long primaryKey = tag.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Tag tag = null;

		try {
			tag = (Tag)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = tag.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TagModelImpl tagModelImpl = this;

		tagModelImpl._originalName = tagModelImpl._name;

		tagModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Tag> toCacheModel() {
		TagCacheModel tagCacheModel = new TagCacheModel();

		tagCacheModel.tagId = getTagId();

		tagCacheModel.name = getName();

		String name = tagCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			tagCacheModel.name = null;
		}

		return tagCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{tagId=");
		sb.append(getTagId());
		sb.append(", name=");
		sb.append(getName());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("it.gebhard.qa.model.Tag");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>tagId</column-name><column-value><![CDATA[");
		sb.append(getTagId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Tag.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Tag.class
		};
	private long _tagId;
	private String _name;
	private String _originalName;
	private long _columnBitmask;
	private Tag _escapedModelProxy;
}